# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StelleriumNetworkInterfacePacket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StelleriumNetworkInterfacePacket.proto',
  package='',
  serialized_pb=_b('\n&StelleriumNetworkInterfacePacket.proto\"A\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x02(\x01\x12\x11\n\tlongitude\x18\x02 \x02(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x02(\x01\"z\n\x16NetworkInterfacePacket\x12\x1b\n\x08location\x18\x01 \x01(\x0b\x32\t.Location\x12\x0c\n\x04time\x18\x02 \x01(\t\x12 \n\x07weather\x18\x03 \x01(\x0e\x32\x08.Weather:\x05\x43LEAR\x12\x13\n\x0bvehicleName\x18\x04 \x01(\t*?\n\x07Weather\x12\t\n\x05\x43LEAR\x10\x00\x12\x0f\n\x0bPART_CLOUDY\x10\x01\x12\n\n\x06\x43LOUDY\x10\x02\x12\x0c\n\x08OVERCAST\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_WEATHER = _descriptor.EnumDescriptor(
  name='Weather',
  full_name='Weather',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLEAR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PART_CLOUDY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUDY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OVERCAST', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=233,
  serialized_end=296,
)
_sym_db.RegisterEnumDescriptor(_WEATHER)

Weather = enum_type_wrapper.EnumTypeWrapper(_WEATHER)
CLEAR = 0
PART_CLOUDY = 1
CLOUDY = 2
OVERCAST = 3



_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Location.latitude', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Location.longitude', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='Location.altitude', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=107,
)


_NETWORKINTERFACEPACKET = _descriptor.Descriptor(
  name='NetworkInterfacePacket',
  full_name='NetworkInterfacePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='NetworkInterfacePacket.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='NetworkInterfacePacket.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weather', full_name='NetworkInterfacePacket.weather', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicleName', full_name='NetworkInterfacePacket.vehicleName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=231,
)

_NETWORKINTERFACEPACKET.fields_by_name['location'].message_type = _LOCATION
_NETWORKINTERFACEPACKET.fields_by_name['weather'].enum_type = _WEATHER
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['NetworkInterfacePacket'] = _NETWORKINTERFACEPACKET
DESCRIPTOR.enum_types_by_name['Weather'] = _WEATHER

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'StelleriumNetworkInterfacePacket_pb2'
  # @@protoc_insertion_point(class_scope:Location)
  ))
_sym_db.RegisterMessage(Location)

NetworkInterfacePacket = _reflection.GeneratedProtocolMessageType('NetworkInterfacePacket', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKINTERFACEPACKET,
  __module__ = 'StelleriumNetworkInterfacePacket_pb2'
  # @@protoc_insertion_point(class_scope:NetworkInterfacePacket)
  ))
_sym_db.RegisterMessage(NetworkInterfacePacket)


# @@protoc_insertion_point(module_scope)
